### ISSUE TITLE
Required files are not in the repository

### ISSUE THREAD

**Issue by RobertCochran** [JoshuaBrockschmidt/twitposter#4]
All of your shell scripts try to source '$(dirname $0)/../twitposter.conf'
(which, ultimately, resolves to /twitposter.conf relative to the repo root).
Because there is no file, bash will very likely exclaim ENOENT ("No such
file or directory"). Even if it doesn't, the non-existent sourced values you're
trying to use will likely to cause things to not go well.

**Comment by jcbrockschmidt** [comment]
You understand that the Makefile is supposed to generate 'twitposter.conf', right? If not, look at the rule 'genConf' on lines 27 through 35.

**Comment by RobertCochran** [comment]
I did not. This is a catchphrase moment.
